// ==========================================================================
//  armour.zs - GENERATED by gen_armour_tooltips.py from the live EnviroMine
//  config. Every line is derived from that item's real numbers, so the text
//  cannot disagree with what the game actually does. Regenerate after any
//  retune; never hand-edit.
//
//  Covers vanilla and hand-tuned sets too - anything with an armour entry.
//  Must be identical on server and every client: tooltips do not sync.
// ==========================================================================

// AWWayofTime:boundBoots
<AWWayofTime:boundBoots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundBoots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// AWWayofTime:boundBootsEarth
<AWWayofTime:boundBootsEarth>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundBootsEarth>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// AWWayofTime:boundBootsFire
<AWWayofTime:boundBootsFire>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<AWWayofTime:boundBootsFire>.addTooltip(format.darkAqua("Also shades you from the sun."));

// AWWayofTime:boundBootsWater
<AWWayofTime:boundBootsWater>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundBootsWater>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// AWWayofTime:boundBootsWind
<AWWayofTime:boundBootsWind>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundBootsWind>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// AWWayofTime:boundHelmet
<AWWayofTime:boundHelmet>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundHelmet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// AWWayofTime:boundHelmetEarth
<AWWayofTime:boundHelmetEarth>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundHelmetEarth>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// AWWayofTime:boundHelmetFire
<AWWayofTime:boundHelmetFire>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<AWWayofTime:boundHelmetFire>.addTooltip(format.darkAqua("Also shades you from the sun."));

// AWWayofTime:boundHelmetWater
<AWWayofTime:boundHelmetWater>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundHelmetWater>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// AWWayofTime:boundHelmetWind
<AWWayofTime:boundHelmetWind>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundHelmetWind>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// AWWayofTime:boundLeggings
<AWWayofTime:boundLeggings>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundLeggings>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// AWWayofTime:boundLeggingsEarth
<AWWayofTime:boundLeggingsEarth>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundLeggingsEarth>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// AWWayofTime:boundLeggingsFire
<AWWayofTime:boundLeggingsFire>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<AWWayofTime:boundLeggingsFire>.addTooltip(format.darkAqua("Also shades you from the sun."));

// AWWayofTime:boundLeggingsWater
<AWWayofTime:boundLeggingsWater>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundLeggingsWater>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// AWWayofTime:boundLeggingsWind
<AWWayofTime:boundLeggingsWind>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundLeggingsWind>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// AWWayofTime:boundPlate
<AWWayofTime:boundPlate>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundPlate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<AWWayofTime:boundPlate>.addTooltip(format.aqua("Carries a camel pack."));

// AWWayofTime:boundPlateEarth
<AWWayofTime:boundPlateEarth>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundPlateEarth>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<AWWayofTime:boundPlateEarth>.addTooltip(format.aqua("Carries a camel pack."));

// AWWayofTime:boundPlateFire
<AWWayofTime:boundPlateFire>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<AWWayofTime:boundPlateFire>.addTooltip(format.darkAqua("Also shades you from the sun."));
<AWWayofTime:boundPlateFire>.addTooltip(format.aqua("Carries a camel pack."));

// AWWayofTime:boundPlateWater
<AWWayofTime:boundPlateWater>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundPlateWater>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<AWWayofTime:boundPlateWater>.addTooltip(format.aqua("Carries a camel pack."));

// AWWayofTime:boundPlateWind
<AWWayofTime:boundPlateWind>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<AWWayofTime:boundPlateWind>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<AWWayofTime:boundPlateWind>.addTooltip(format.aqua("Carries a camel pack."));

// AWWayofTime:sanguineBoots
<AWWayofTime:sanguineBoots>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<AWWayofTime:sanguineBoots>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// AWWayofTime:sanguineHelmet
<AWWayofTime:sanguineHelmet>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<AWWayofTime:sanguineHelmet>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// AWWayofTime:sanguinePants
<AWWayofTime:sanguinePants>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<AWWayofTime:sanguinePants>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// AWWayofTime:sanguineRobe
<AWWayofTime:sanguineRobe>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<AWWayofTime:sanguineRobe>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<AWWayofTime:sanguineRobe>.addTooltip(format.aqua("Carries a camel pack."));

// Aquaculture:item.NeptuniumBoots
<Aquaculture:item.NeptuniumBoots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Aquaculture:item.NeptuniumHelmet
<Aquaculture:item.NeptuniumHelmet>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Aquaculture:item.NeptuniumLegs
<Aquaculture:item.NeptuniumLegs>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Aquaculture:item.NeptuniumPlate
<Aquaculture:item.NeptuniumPlate>.addTooltip(format.darkAqua("Also shades you from the sun."));
<Aquaculture:item.NeptuniumPlate>.addTooltip(format.aqua("Carries a camel pack."));

// BloodArsenal:glass_boots
<BloodArsenal:glass_boots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<BloodArsenal:glass_boots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// BloodArsenal:glass_chestplate
<BloodArsenal:glass_chestplate>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<BloodArsenal:glass_chestplate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<BloodArsenal:glass_chestplate>.addTooltip(format.aqua("Carries a camel pack."));

// BloodArsenal:glass_helmet
<BloodArsenal:glass_helmet>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<BloodArsenal:glass_helmet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// BloodArsenal:glass_leggings
<BloodArsenal:glass_leggings>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<BloodArsenal:glass_leggings>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// BloodArsenal:life_imbued_boots
<BloodArsenal:life_imbued_boots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<BloodArsenal:life_imbued_boots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// BloodArsenal:life_imbued_chestplate
<BloodArsenal:life_imbued_chestplate>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<BloodArsenal:life_imbued_chestplate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<BloodArsenal:life_imbued_chestplate>.addTooltip(format.aqua("Carries a camel pack."));

// BloodArsenal:life_imbued_helmet
<BloodArsenal:life_imbued_helmet>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<BloodArsenal:life_imbued_helmet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// BloodArsenal:life_imbued_leggings
<BloodArsenal:life_imbued_leggings>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<BloodArsenal:life_imbued_leggings>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// BloodArsenal:vampire_boots
<BloodArsenal:vampire_boots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<BloodArsenal:vampire_boots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// BloodArsenal:vampire_greaves
<BloodArsenal:vampire_greaves>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<BloodArsenal:vampire_greaves>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// Botania:elementiumBoots
<Botania:elementiumBoots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Botania:elementiumChest
<Botania:elementiumChest>.addTooltip(format.darkAqua("Also shades you from the sun."));
<Botania:elementiumChest>.addTooltip(format.aqua("Carries a camel pack."));

// Botania:elementiumHelm
<Botania:elementiumHelm>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Botania:elementiumHelmReveal
<Botania:elementiumHelmReveal>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Botania:elementiumLegs
<Botania:elementiumLegs>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Botania:manasteelBoots
<Botania:manasteelBoots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Botania:manasteelChest
<Botania:manasteelChest>.addTooltip(format.darkAqua("Also shades you from the sun."));
<Botania:manasteelChest>.addTooltip(format.aqua("Carries a camel pack."));

// Botania:manasteelHelm
<Botania:manasteelHelm>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Botania:manasteelHelmReveal
<Botania:manasteelHelmReveal>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Botania:manasteelLegs
<Botania:manasteelLegs>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Botania:manaweaveBoots
<Botania:manaweaveBoots>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Botania:manaweaveBoots>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Botania:manaweaveChest
<Botania:manaweaveChest>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Botania:manaweaveChest>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<Botania:manaweaveChest>.addTooltip(format.aqua("Carries a camel pack."));

// Botania:manaweaveHelm
<Botania:manaweaveHelm>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Botania:manaweaveHelm>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Botania:manaweaveLegs
<Botania:manaweaveLegs>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Botania:manaweaveLegs>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Botania:terrasteelBoots
<Botania:terrasteelBoots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Botania:terrasteelChest
<Botania:terrasteelChest>.addTooltip(format.darkAqua("Also shades you from the sun."));
<Botania:terrasteelChest>.addTooltip(format.aqua("Carries a camel pack."));

// Botania:terrasteelHelm
<Botania:terrasteelHelm>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Botania:terrasteelHelmReveal
<Botania:terrasteelHelmReveal>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Botania:terrasteelLegs
<Botania:terrasteelLegs>.addTooltip(format.darkAqua("Also shades you from the sun."));

// CompactSolars:solarHatHV
<CompactSolars:solarHatHV>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<CompactSolars:solarHatHV>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// CompactSolars:solarHatLV
<CompactSolars:solarHatLV>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<CompactSolars:solarHatLV>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// CompactSolars:solarHatMV
<CompactSolars:solarHatMV>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<CompactSolars:solarHatMV>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// EnderIO:item.darkSteel_boots
<EnderIO:item.darkSteel_boots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// EnderIO:item.darkSteel_chestplate
<EnderIO:item.darkSteel_chestplate>.addTooltip(format.darkAqua("Also shades you from the sun."));
<EnderIO:item.darkSteel_chestplate>.addTooltip(format.aqua("Carries a camel pack."));

// EnderIO:item.darkSteel_helmet
<EnderIO:item.darkSteel_helmet>.addTooltip(format.darkAqua("Also shades you from the sun."));

// EnderIO:item.darkSteel_leggings
<EnderIO:item.darkSteel_leggings>.addTooltip(format.darkAqua("Also shades you from the sun."));

// ExtraUtilities:sonar_goggles
<ExtraUtilities:sonar_goggles>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<ExtraUtilities:sonar_goggles>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// Forestry:apiaristBoots
<Forestry:apiaristBoots>.addTooltip(format.aqua("Warm at night. Hot in the sun."));
<Forestry:apiaristBoots>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Forestry:apiaristChest
<Forestry:apiaristChest>.addTooltip(format.aqua("Warm at night. Hot in the sun."));
<Forestry:apiaristChest>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<Forestry:apiaristChest>.addTooltip(format.aqua("Carries a camel pack."));

// Forestry:apiaristHelmet
<Forestry:apiaristHelmet>.addTooltip(format.aqua("Warm at night. Hot in the sun."));
<Forestry:apiaristHelmet>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Forestry:apiaristLegs
<Forestry:apiaristLegs>.addTooltip(format.aqua("Warm at night. Hot in the sun."));
<Forestry:apiaristLegs>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Forestry:naturalistHelmet
<Forestry:naturalistHelmet>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<Forestry:naturalistHelmet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// IC2:itemArmorAlloyChestplate
<IC2:itemArmorAlloyChestplate>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<IC2:itemArmorAlloyChestplate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<IC2:itemArmorAlloyChestplate>.addTooltip(format.aqua("Carries a camel pack."));

// IC2:itemArmorBronzeBoots
<IC2:itemArmorBronzeBoots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<IC2:itemArmorBronzeBoots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// IC2:itemArmorBronzeChestplate
<IC2:itemArmorBronzeChestplate>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<IC2:itemArmorBronzeChestplate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<IC2:itemArmorBronzeChestplate>.addTooltip(format.aqua("Carries a camel pack."));

// IC2:itemArmorBronzeHelmet
<IC2:itemArmorBronzeHelmet>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<IC2:itemArmorBronzeHelmet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// IC2:itemArmorBronzeLegs
<IC2:itemArmorBronzeLegs>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<IC2:itemArmorBronzeLegs>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// IC2:itemArmorHazmatChestplate
<IC2:itemArmorHazmatChestplate>.addTooltip(format.green("Filters some foul air."));
<IC2:itemArmorHazmatChestplate>.addTooltip(format.aqua("Carries a camel pack."));

// IC2:itemArmorHazmatHelmet
<IC2:itemArmorHazmatHelmet>.addTooltip(format.green("Filters foul air. Full protection."));

// IC2:itemArmorHazmatLeggings
<IC2:itemArmorHazmatLeggings>.addTooltip(format.green("Filters some foul air."));

// IC2:itemArmorNanoBoots
<IC2:itemArmorNanoBoots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<IC2:itemArmorNanoBoots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// IC2:itemArmorNanoChestplate
<IC2:itemArmorNanoChestplate>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<IC2:itemArmorNanoChestplate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<IC2:itemArmorNanoChestplate>.addTooltip(format.aqua("Carries a camel pack."));

// IC2:itemArmorNanoHelmet
<IC2:itemArmorNanoHelmet>.addTooltip(format.darkAqua("Also shades you from the sun."));
<IC2:itemArmorNanoHelmet>.addTooltip(format.green("Filters some foul air."));

// IC2:itemArmorNanoLegs
<IC2:itemArmorNanoLegs>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<IC2:itemArmorNanoLegs>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// IC2:itemArmorQuantumBoots
<IC2:itemArmorQuantumBoots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// IC2:itemArmorQuantumChestplate
<IC2:itemArmorQuantumChestplate>.addTooltip(format.darkAqua("Also shades you from the sun."));
<IC2:itemArmorQuantumChestplate>.addTooltip(format.aqua("Carries a camel pack."));

// IC2:itemArmorQuantumHelmet
<IC2:itemArmorQuantumHelmet>.addTooltip(format.darkAqua("Also shades you from the sun."));
<IC2:itemArmorQuantumHelmet>.addTooltip(format.green("Filters foul air. Full protection."));

// IC2:itemArmorQuantumLegs
<IC2:itemArmorQuantumLegs>.addTooltip(format.darkAqua("Also shades you from the sun."));

// IC2:itemArmorRubBoots
<IC2:itemArmorRubBoots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<IC2:itemArmorRubBoots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// IC2:itemNightvisionGoggles
<IC2:itemNightvisionGoggles>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<IC2:itemNightvisionGoggles>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// IC2:itemSolarHelmet
<IC2:itemSolarHelmet>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<IC2:itemSolarHelmet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// IC2:itemStaticBoots
<IC2:itemStaticBoots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<IC2:itemStaticBoots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// MoCreatures:elephantchest
<MoCreatures:elephantchest>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<MoCreatures:elephantchest>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<MoCreatures:elephantchest>.addTooltip(format.aqua("Carries a camel pack."));

// MoCreatures:furboots
<MoCreatures:furboots>.addTooltip(format.aqua("Warm at night."));
<MoCreatures:furboots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// MoCreatures:furchest
<MoCreatures:furchest>.addTooltip(format.aqua("Warm at night."));
<MoCreatures:furchest>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<MoCreatures:furchest>.addTooltip(format.aqua("Carries a camel pack."));

// MoCreatures:furhelmet
<MoCreatures:furhelmet>.addTooltip(format.aqua("Warm at night."));
<MoCreatures:furhelmet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// MoCreatures:furlegs
<MoCreatures:furlegs>.addTooltip(format.aqua("Warm at night."));
<MoCreatures:furlegs>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// MoCreatures:hideboots
<MoCreatures:hideboots>.addTooltip(format.aqua("Slightly warm at night. Slightly hot in the sun."));

// MoCreatures:hidechest
<MoCreatures:hidechest>.addTooltip(format.aqua("Slightly warm at night. Slightly hot in the sun."));
<MoCreatures:hidechest>.addTooltip(format.aqua("Carries a camel pack."));

// MoCreatures:hidehelmet
<MoCreatures:hidehelmet>.addTooltip(format.aqua("Slightly warm at night. Slightly hot in the sun."));

// MoCreatures:hidelegs
<MoCreatures:hidelegs>.addTooltip(format.aqua("Slightly warm at night. Slightly hot in the sun."));

// MoCreatures:reptileboots
<MoCreatures:reptileboots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<MoCreatures:reptileboots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// MoCreatures:reptilehelmet
<MoCreatures:reptilehelmet>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<MoCreatures:reptilehelmet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// MoCreatures:reptilelegs
<MoCreatures:reptilelegs>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<MoCreatures:reptilelegs>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// MoCreatures:reptileplate
<MoCreatures:reptileplate>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<MoCreatures:reptileplate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<MoCreatures:reptileplate>.addTooltip(format.aqua("Carries a camel pack."));

// MoCreatures:scorpbootscave
<MoCreatures:scorpbootscave>.addTooltip(format.green("Filters some foul air."));

// MoCreatures:scorpbootsdirt
<MoCreatures:scorpbootsdirt>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// MoCreatures:scorpbootsfrost
<MoCreatures:scorpbootsfrost>.addTooltip(format.aqua("Very warm at night."));
<MoCreatures:scorpbootsfrost>.addTooltip(format.darkAqua("Also insulates against cold."));

// MoCreatures:scorpbootsnether
<MoCreatures:scorpbootsnether>.addTooltip(format.gold("Slightly cool in the sun."));
<MoCreatures:scorpbootsnether>.addTooltip(format.darkAqua("Also shades you from the sun."));

// MoCreatures:scorphelmetcave
<MoCreatures:scorphelmetcave>.addTooltip(format.green("Filters foul air. Full protection."));

// MoCreatures:scorphelmetdirt
<MoCreatures:scorphelmetdirt>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// MoCreatures:scorphelmetfrost
<MoCreatures:scorphelmetfrost>.addTooltip(format.aqua("Very warm at night."));
<MoCreatures:scorphelmetfrost>.addTooltip(format.darkAqua("Also insulates against cold."));

// MoCreatures:scorphelmetnether
<MoCreatures:scorphelmetnether>.addTooltip(format.gold("Slightly cool in the sun."));
<MoCreatures:scorphelmetnether>.addTooltip(format.darkAqua("Also shades you from the sun."));

// MoCreatures:scorplegscave
<MoCreatures:scorplegscave>.addTooltip(format.green("Filters some foul air."));

// MoCreatures:scorplegsdirt
<MoCreatures:scorplegsdirt>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// MoCreatures:scorplegsfrost
<MoCreatures:scorplegsfrost>.addTooltip(format.aqua("Very warm at night."));
<MoCreatures:scorplegsfrost>.addTooltip(format.darkAqua("Also insulates against cold."));

// MoCreatures:scorplegsnether
<MoCreatures:scorplegsnether>.addTooltip(format.gold("Slightly cool in the sun."));
<MoCreatures:scorplegsnether>.addTooltip(format.darkAqua("Also shades you from the sun."));

// MoCreatures:scorpplatecave
<MoCreatures:scorpplatecave>.addTooltip(format.green("Filters some foul air."));
<MoCreatures:scorpplatecave>.addTooltip(format.aqua("Carries a camel pack."));

// MoCreatures:scorpplatedirt
<MoCreatures:scorpplatedirt>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));
<MoCreatures:scorpplatedirt>.addTooltip(format.aqua("Carries a camel pack."));

// MoCreatures:scorpplatefrost
<MoCreatures:scorpplatefrost>.addTooltip(format.aqua("Very warm at night."));
<MoCreatures:scorpplatefrost>.addTooltip(format.darkAqua("Also insulates against cold."));
<MoCreatures:scorpplatefrost>.addTooltip(format.aqua("Carries a camel pack."));

// MoCreatures:scorpplatenether
<MoCreatures:scorpplatenether>.addTooltip(format.gold("Slightly cool in the sun."));
<MoCreatures:scorpplatenether>.addTooltip(format.darkAqua("Also shades you from the sun."));
<MoCreatures:scorpplatenether>.addTooltip(format.aqua("Carries a camel pack."));

// Natura:natura.armor.impboots
<Natura:natura.armor.impboots>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<Natura:natura.armor.impboots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Natura:natura.armor.imphelmet
<Natura:natura.armor.imphelmet>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<Natura:natura.armor.imphelmet>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Natura:natura.armor.impjerkin
<Natura:natura.armor.impjerkin>.addTooltip(format.aqua("Warm at night. Hot in the sun."));
<Natura:natura.armor.impjerkin>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<Natura:natura.armor.impjerkin>.addTooltip(format.aqua("Carries a camel pack."));

// Natura:natura.armor.impleggings
<Natura:natura.armor.impleggings>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<Natura:natura.armor.impleggings>.addTooltip(format.darkAqua("Also shades you from the sun."));

// NuclearCraft:boronBoots
<NuclearCraft:boronBoots>.addTooltip(format.aqua("Warm at night."));
<NuclearCraft:boronBoots>.addTooltip(format.green("Filters some foul air."));

// NuclearCraft:boronChest
<NuclearCraft:boronChest>.addTooltip(format.aqua("Warm at night."));
<NuclearCraft:boronChest>.addTooltip(format.green("Filters some foul air."));
<NuclearCraft:boronChest>.addTooltip(format.aqua("Carries a camel pack."));

// NuclearCraft:boronHelm
<NuclearCraft:boronHelm>.addTooltip(format.aqua("Warm at night."));
<NuclearCraft:boronHelm>.addTooltip(format.green("Filters some foul air."));

// NuclearCraft:boronLegs
<NuclearCraft:boronLegs>.addTooltip(format.aqua("Warm at night."));
<NuclearCraft:boronLegs>.addTooltip(format.green("Filters some foul air."));

// NuclearCraft:bronzeBoots
<NuclearCraft:bronzeBoots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<NuclearCraft:bronzeBoots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// NuclearCraft:bronzeChest
<NuclearCraft:bronzeChest>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<NuclearCraft:bronzeChest>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<NuclearCraft:bronzeChest>.addTooltip(format.aqua("Carries a camel pack."));

// NuclearCraft:bronzeHelm
<NuclearCraft:bronzeHelm>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<NuclearCraft:bronzeHelm>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// NuclearCraft:bronzeLegs
<NuclearCraft:bronzeLegs>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<NuclearCraft:bronzeLegs>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// NuclearCraft:dUBoots
<NuclearCraft:dUBoots>.addTooltip(format.aqua("Warm at night."));
<NuclearCraft:dUBoots>.addTooltip(format.green("Filters some foul air."));

// NuclearCraft:dUChest
<NuclearCraft:dUChest>.addTooltip(format.aqua("Warm at night."));
<NuclearCraft:dUChest>.addTooltip(format.green("Filters some foul air."));
<NuclearCraft:dUChest>.addTooltip(format.aqua("Carries a camel pack."));

// NuclearCraft:dUHelm
<NuclearCraft:dUHelm>.addTooltip(format.aqua("Warm at night."));
<NuclearCraft:dUHelm>.addTooltip(format.green("Filters some foul air."));

// NuclearCraft:dULegs
<NuclearCraft:dULegs>.addTooltip(format.aqua("Warm at night."));
<NuclearCraft:dULegs>.addTooltip(format.green("Filters some foul air."));

// NuclearCraft:toughBoots
<NuclearCraft:toughBoots>.addTooltip(format.aqua("Warm at night."));
<NuclearCraft:toughBoots>.addTooltip(format.green("Filters some foul air."));

// NuclearCraft:toughChest
<NuclearCraft:toughChest>.addTooltip(format.aqua("Warm at night."));
<NuclearCraft:toughChest>.addTooltip(format.green("Filters some foul air."));
<NuclearCraft:toughChest>.addTooltip(format.aqua("Carries a camel pack."));

// NuclearCraft:toughHelm
<NuclearCraft:toughHelm>.addTooltip(format.aqua("Warm at night."));
<NuclearCraft:toughHelm>.addTooltip(format.green("Filters some foul air."));

// NuclearCraft:toughLegs
<NuclearCraft:toughLegs>.addTooltip(format.aqua("Warm at night."));
<NuclearCraft:toughLegs>.addTooltip(format.green("Filters some foul air."));

// OpenComputers:hoverBoots
<OpenComputers:hoverBoots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<OpenComputers:hoverBoots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// Railcraft:armor.goggles
<Railcraft:armor.goggles>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<Railcraft:armor.goggles>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// Railcraft:armor.overalls
<Railcraft:armor.overalls>.addTooltip(format.aqua("Warm at night. Hot in the sun."));
<Railcraft:armor.overalls>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<Railcraft:armor.overalls>.addTooltip(format.aqua("Carries a camel pack."));

// Railcraft:armor.steel.boots
<Railcraft:armor.steel.boots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Railcraft:armor.steel.helmet
<Railcraft:armor.steel.helmet>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Railcraft:armor.steel.legs
<Railcraft:armor.steel.legs>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Railcraft:armor.steel.plate
<Railcraft:armor.steel.plate>.addTooltip(format.darkAqua("Also shades you from the sun."));
<Railcraft:armor.steel.plate>.addTooltip(format.aqua("Carries a camel pack."));

// RandomThings:creativeChestGenerator
<RandomThings:creativeChestGenerator>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<RandomThings:creativeChestGenerator>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<RandomThings:creativeChestGenerator>.addTooltip(format.aqua("Carries a camel pack."));

// RandomThings:spectreBoots
<RandomThings:spectreBoots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// RandomThings:spectreChestplate
<RandomThings:spectreChestplate>.addTooltip(format.darkAqua("Also shades you from the sun."));
<RandomThings:spectreChestplate>.addTooltip(format.aqua("Carries a camel pack."));

// RandomThings:spectreHelmet
<RandomThings:spectreHelmet>.addTooltip(format.darkAqua("Also shades you from the sun."));

// RandomThings:spectreLeggings
<RandomThings:spectreLeggings>.addTooltip(format.darkAqua("Also shades you from the sun."));

// TConstruct:bootsWood
<TConstruct:bootsWood>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TConstruct:bootsWood>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TConstruct:chestplateWood
<TConstruct:chestplateWood>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TConstruct:chestplateWood>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<TConstruct:chestplateWood>.addTooltip(format.aqua("Carries a camel pack."));

// TConstruct:hatchet
<TConstruct:hatchet>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TConstruct:hatchet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TConstruct:hatchetHead
<TConstruct:hatchetHead>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TConstruct:hatchetHead>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TConstruct:heavyPlate
<TConstruct:heavyPlate>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TConstruct:heavyPlate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<TConstruct:heavyPlate>.addTooltip(format.aqua("Carries a camel pack."));

// TConstruct:helmetWood
<TConstruct:helmetWood>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TConstruct:helmetWood>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TConstruct:leggingsWood
<TConstruct:leggingsWood>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TConstruct:leggingsWood>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TConstruct:travelBoots
<TConstruct:travelBoots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TConstruct:travelBoots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TConstruct:travelGoggles
<TConstruct:travelGoggles>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TConstruct:travelGoggles>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TConstruct:travelVest
<TConstruct:travelVest>.addTooltip(format.aqua("Warm at night. Hot in the sun."));
<TConstruct:travelVest>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<TConstruct:travelVest>.addTooltip(format.aqua("Carries a camel pack."));

// Thaumcraft:BootsTraveller
<Thaumcraft:BootsTraveller>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<Thaumcraft:BootsTraveller>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// Thaumcraft:ItemBootsCultist
<Thaumcraft:ItemBootsCultist>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Thaumcraft:ItemBootsCultist>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Thaumcraft:ItemBootsRobe
<Thaumcraft:ItemBootsRobe>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Thaumcraft:ItemBootsRobe>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Thaumcraft:ItemBootsThaumium
<Thaumcraft:ItemBootsThaumium>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Thaumcraft:ItemBootsVoid
<Thaumcraft:ItemBootsVoid>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Thaumcraft:ItemChestplateCultistLeaderPlate
<Thaumcraft:ItemChestplateCultistLeaderPlate>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Thaumcraft:ItemChestplateCultistLeaderPlate>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<Thaumcraft:ItemChestplateCultistLeaderPlate>.addTooltip(format.aqua("Carries a camel pack."));

// Thaumcraft:ItemChestplateCultistPlate
<Thaumcraft:ItemChestplateCultistPlate>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Thaumcraft:ItemChestplateCultistPlate>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<Thaumcraft:ItemChestplateCultistPlate>.addTooltip(format.aqua("Carries a camel pack."));

// Thaumcraft:ItemChestplateCultistRobe
<Thaumcraft:ItemChestplateCultistRobe>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Thaumcraft:ItemChestplateCultistRobe>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<Thaumcraft:ItemChestplateCultistRobe>.addTooltip(format.aqua("Carries a camel pack."));

// Thaumcraft:ItemChestplateFortress
<Thaumcraft:ItemChestplateFortress>.addTooltip(format.darkAqua("Also shades you from the sun."));
<Thaumcraft:ItemChestplateFortress>.addTooltip(format.aqua("Carries a camel pack."));

// Thaumcraft:ItemChestplateRobe
<Thaumcraft:ItemChestplateRobe>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Thaumcraft:ItemChestplateRobe>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<Thaumcraft:ItemChestplateRobe>.addTooltip(format.aqua("Carries a camel pack."));

// Thaumcraft:ItemChestplateThaumium
<Thaumcraft:ItemChestplateThaumium>.addTooltip(format.darkAqua("Also shades you from the sun."));
<Thaumcraft:ItemChestplateThaumium>.addTooltip(format.aqua("Carries a camel pack."));

// Thaumcraft:ItemChestplateVoid
<Thaumcraft:ItemChestplateVoid>.addTooltip(format.darkAqua("Also shades you from the sun."));
<Thaumcraft:ItemChestplateVoid>.addTooltip(format.aqua("Carries a camel pack."));

// Thaumcraft:ItemChestplateVoidFortress
<Thaumcraft:ItemChestplateVoidFortress>.addTooltip(format.darkAqua("Also shades you from the sun."));
<Thaumcraft:ItemChestplateVoidFortress>.addTooltip(format.aqua("Carries a camel pack."));

// Thaumcraft:ItemGoggles
<Thaumcraft:ItemGoggles>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<Thaumcraft:ItemGoggles>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// Thaumcraft:ItemHelmetCultistLeaderPlate
<Thaumcraft:ItemHelmetCultistLeaderPlate>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Thaumcraft:ItemHelmetCultistLeaderPlate>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Thaumcraft:ItemHelmetCultistPlate
<Thaumcraft:ItemHelmetCultistPlate>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Thaumcraft:ItemHelmetCultistPlate>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Thaumcraft:ItemHelmetCultistRobe
<Thaumcraft:ItemHelmetCultistRobe>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Thaumcraft:ItemHelmetCultistRobe>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Thaumcraft:ItemHelmetFortress
<Thaumcraft:ItemHelmetFortress>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Thaumcraft:ItemHelmetThaumium
<Thaumcraft:ItemHelmetThaumium>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Thaumcraft:ItemHelmetVoid
<Thaumcraft:ItemHelmetVoid>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Thaumcraft:ItemHelmetVoidFortress
<Thaumcraft:ItemHelmetVoidFortress>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Thaumcraft:ItemLeggingsCultistLeaderPlate
<Thaumcraft:ItemLeggingsCultistLeaderPlate>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Thaumcraft:ItemLeggingsCultistLeaderPlate>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Thaumcraft:ItemLeggingsCultistPlate
<Thaumcraft:ItemLeggingsCultistPlate>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Thaumcraft:ItemLeggingsCultistPlate>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Thaumcraft:ItemLeggingsCultistRobe
<Thaumcraft:ItemLeggingsCultistRobe>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Thaumcraft:ItemLeggingsCultistRobe>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Thaumcraft:ItemLeggingsFortress
<Thaumcraft:ItemLeggingsFortress>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Thaumcraft:ItemLeggingsRobe
<Thaumcraft:ItemLeggingsRobe>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<Thaumcraft:ItemLeggingsRobe>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// Thaumcraft:ItemLeggingsThaumium
<Thaumcraft:ItemLeggingsThaumium>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Thaumcraft:ItemLeggingsVoid
<Thaumcraft:ItemLeggingsVoid>.addTooltip(format.darkAqua("Also shades you from the sun."));

// Thaumcraft:ItemLeggingsVoidFortress
<Thaumcraft:ItemLeggingsVoidFortress>.addTooltip(format.darkAqua("Also shades you from the sun."));

// ThaumicTinkerer:focusEnderChest
<ThaumicTinkerer:focusEnderChest>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<ThaumicTinkerer:focusEnderChest>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<ThaumicTinkerer:focusEnderChest>.addTooltip(format.aqua("Carries a camel pack."));

// ThaumicTinkerer:ichorclothBoots
<ThaumicTinkerer:ichorclothBoots>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<ThaumicTinkerer:ichorclothBoots>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// ThaumicTinkerer:ichorclothBootsGem
<ThaumicTinkerer:ichorclothBootsGem>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<ThaumicTinkerer:ichorclothBootsGem>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// ThaumicTinkerer:ichorclothChest
<ThaumicTinkerer:ichorclothChest>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<ThaumicTinkerer:ichorclothChest>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<ThaumicTinkerer:ichorclothChest>.addTooltip(format.aqua("Carries a camel pack."));

// ThaumicTinkerer:ichorclothChestGem
<ThaumicTinkerer:ichorclothChestGem>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<ThaumicTinkerer:ichorclothChestGem>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<ThaumicTinkerer:ichorclothChestGem>.addTooltip(format.aqua("Carries a camel pack."));

// ThaumicTinkerer:ichorclothHelm
<ThaumicTinkerer:ichorclothHelm>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<ThaumicTinkerer:ichorclothHelm>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// ThaumicTinkerer:ichorclothHelmGem
<ThaumicTinkerer:ichorclothHelmGem>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<ThaumicTinkerer:ichorclothHelmGem>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// ThaumicTinkerer:ichorclothLegs
<ThaumicTinkerer:ichorclothLegs>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<ThaumicTinkerer:ichorclothLegs>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// ThaumicTinkerer:ichorclothLegsGem
<ThaumicTinkerer:ichorclothLegsGem>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<ThaumicTinkerer:ichorclothLegsGem>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// ThaumicTinkerer:revealingHelm
<ThaumicTinkerer:revealingHelm>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<ThaumicTinkerer:revealingHelm>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.bootsBronze
<ThermalFoundation:armor.bootsBronze>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<ThermalFoundation:armor.bootsBronze>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.bootsCopper
<ThermalFoundation:armor.bootsCopper>.addTooltip(format.gray("Slightly cold at night. Hot in the sun."));
<ThermalFoundation:armor.bootsCopper>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.bootsElectrum
<ThermalFoundation:armor.bootsElectrum>.addTooltip(format.gold("Punishing in the sun."));
<ThermalFoundation:armor.bootsElectrum>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.bootsInvar
<ThermalFoundation:armor.bootsInvar>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// ThermalFoundation:armor.bootsLead
<ThermalFoundation:armor.bootsLead>.addTooltip(format.gold("Hot in the sun."));
<ThermalFoundation:armor.bootsLead>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.bootsNickel
<ThermalFoundation:armor.bootsNickel>.addTooltip(format.aqua("Very warm at night."));

// ThermalFoundation:armor.bootsPlatinum
<ThermalFoundation:armor.bootsPlatinum>.addTooltip(format.darkAqua("Also shades you from the sun."));

// ThermalFoundation:armor.bootsSilver
<ThermalFoundation:armor.bootsSilver>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<ThermalFoundation:armor.bootsSilver>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.bootsTin
<ThermalFoundation:armor.bootsTin>.addTooltip(format.gray("Cold at night. Cool in the sun."));
<ThermalFoundation:armor.bootsTin>.addTooltip(format.darkAqua("Also shades you from the sun."));

// ThermalFoundation:armor.helmetBronze
<ThermalFoundation:armor.helmetBronze>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<ThermalFoundation:armor.helmetBronze>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.helmetCopper
<ThermalFoundation:armor.helmetCopper>.addTooltip(format.gray("Slightly cold at night. Hot in the sun."));
<ThermalFoundation:armor.helmetCopper>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.helmetElectrum
<ThermalFoundation:armor.helmetElectrum>.addTooltip(format.gold("Punishing in the sun."));
<ThermalFoundation:armor.helmetElectrum>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.helmetInvar
<ThermalFoundation:armor.helmetInvar>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// ThermalFoundation:armor.helmetLead
<ThermalFoundation:armor.helmetLead>.addTooltip(format.gold("Hot in the sun."));
<ThermalFoundation:armor.helmetLead>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<ThermalFoundation:armor.helmetLead>.addTooltip(format.green("Filters foul air. Full protection."));

// ThermalFoundation:armor.helmetNickel
<ThermalFoundation:armor.helmetNickel>.addTooltip(format.aqua("Very warm at night."));

// ThermalFoundation:armor.helmetPlatinum
<ThermalFoundation:armor.helmetPlatinum>.addTooltip(format.darkAqua("Also shades you from the sun."));

// ThermalFoundation:armor.helmetSilver
<ThermalFoundation:armor.helmetSilver>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<ThermalFoundation:armor.helmetSilver>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.helmetTin
<ThermalFoundation:armor.helmetTin>.addTooltip(format.gray("Cold at night. Cool in the sun."));
<ThermalFoundation:armor.helmetTin>.addTooltip(format.darkAqua("Also shades you from the sun."));

// ThermalFoundation:armor.legsBronze
<ThermalFoundation:armor.legsBronze>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<ThermalFoundation:armor.legsBronze>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.legsCopper
<ThermalFoundation:armor.legsCopper>.addTooltip(format.gray("Slightly cold at night. Hot in the sun."));
<ThermalFoundation:armor.legsCopper>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.legsElectrum
<ThermalFoundation:armor.legsElectrum>.addTooltip(format.gold("Punishing in the sun."));
<ThermalFoundation:armor.legsElectrum>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.legsInvar
<ThermalFoundation:armor.legsInvar>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// ThermalFoundation:armor.legsLead
<ThermalFoundation:armor.legsLead>.addTooltip(format.gold("Hot in the sun."));
<ThermalFoundation:armor.legsLead>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.legsNickel
<ThermalFoundation:armor.legsNickel>.addTooltip(format.aqua("Very warm at night."));

// ThermalFoundation:armor.legsPlatinum
<ThermalFoundation:armor.legsPlatinum>.addTooltip(format.darkAqua("Also shades you from the sun."));

// ThermalFoundation:armor.legsSilver
<ThermalFoundation:armor.legsSilver>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<ThermalFoundation:armor.legsSilver>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// ThermalFoundation:armor.legsTin
<ThermalFoundation:armor.legsTin>.addTooltip(format.gray("Cold at night. Cool in the sun."));
<ThermalFoundation:armor.legsTin>.addTooltip(format.darkAqua("Also shades you from the sun."));

// ThermalFoundation:armor.plateBronze
<ThermalFoundation:armor.plateBronze>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<ThermalFoundation:armor.plateBronze>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<ThermalFoundation:armor.plateBronze>.addTooltip(format.aqua("Carries a camel pack."));

// ThermalFoundation:armor.plateCopper
<ThermalFoundation:armor.plateCopper>.addTooltip(format.gray("Slightly cold at night. Hot in the sun."));
<ThermalFoundation:armor.plateCopper>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<ThermalFoundation:armor.plateCopper>.addTooltip(format.aqua("Carries a camel pack."));

// ThermalFoundation:armor.plateElectrum
<ThermalFoundation:armor.plateElectrum>.addTooltip(format.gold("Punishing in the sun."));
<ThermalFoundation:armor.plateElectrum>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<ThermalFoundation:armor.plateElectrum>.addTooltip(format.aqua("Carries a camel pack."));

// ThermalFoundation:armor.plateInvar
<ThermalFoundation:armor.plateInvar>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));
<ThermalFoundation:armor.plateInvar>.addTooltip(format.aqua("Carries a camel pack."));

// ThermalFoundation:armor.plateLead
<ThermalFoundation:armor.plateLead>.addTooltip(format.gold("Hot in the sun."));
<ThermalFoundation:armor.plateLead>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<ThermalFoundation:armor.plateLead>.addTooltip(format.aqua("Carries a camel pack."));

// ThermalFoundation:armor.plateNickel
<ThermalFoundation:armor.plateNickel>.addTooltip(format.aqua("Very warm at night."));
<ThermalFoundation:armor.plateNickel>.addTooltip(format.aqua("Carries a camel pack."));

// ThermalFoundation:armor.platePlatinum
<ThermalFoundation:armor.platePlatinum>.addTooltip(format.darkAqua("Also shades you from the sun."));
<ThermalFoundation:armor.platePlatinum>.addTooltip(format.aqua("Carries a camel pack."));

// ThermalFoundation:armor.plateSilver
<ThermalFoundation:armor.plateSilver>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<ThermalFoundation:armor.plateSilver>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<ThermalFoundation:armor.plateSilver>.addTooltip(format.aqua("Carries a camel pack."));

// ThermalFoundation:armor.plateTin
<ThermalFoundation:armor.plateTin>.addTooltip(format.gray("Cold at night. Cool in the sun."));
<ThermalFoundation:armor.plateTin>.addTooltip(format.darkAqua("Also shades you from the sun."));
<ThermalFoundation:armor.plateTin>.addTooltip(format.aqua("Carries a camel pack."));

// TwilightForest:item.arcticBoots
<TwilightForest:item.arcticBoots>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<TwilightForest:item.arcticBoots>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// TwilightForest:item.arcticHelm
<TwilightForest:item.arcticHelm>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<TwilightForest:item.arcticHelm>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// TwilightForest:item.arcticLegs
<TwilightForest:item.arcticLegs>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<TwilightForest:item.arcticLegs>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// TwilightForest:item.arcticPlate
<TwilightForest:item.arcticPlate>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<TwilightForest:item.arcticPlate>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<TwilightForest:item.arcticPlate>.addTooltip(format.aqua("Carries a camel pack."));

// TwilightForest:item.fieryBoots
<TwilightForest:item.fieryBoots>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<TwilightForest:item.fieryBoots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// TwilightForest:item.fieryHelm
<TwilightForest:item.fieryHelm>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<TwilightForest:item.fieryHelm>.addTooltip(format.darkAqua("Also shades you from the sun."));

// TwilightForest:item.fieryLegs
<TwilightForest:item.fieryLegs>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<TwilightForest:item.fieryLegs>.addTooltip(format.darkAqua("Also shades you from the sun."));

// TwilightForest:item.fieryPlate
<TwilightForest:item.fieryPlate>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<TwilightForest:item.fieryPlate>.addTooltip(format.darkAqua("Also shades you from the sun."));
<TwilightForest:item.fieryPlate>.addTooltip(format.aqua("Carries a camel pack."));

// TwilightForest:item.ironwoodBoots
<TwilightForest:item.ironwoodBoots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TwilightForest:item.ironwoodBoots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TwilightForest:item.ironwoodHelm
<TwilightForest:item.ironwoodHelm>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TwilightForest:item.ironwoodHelm>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TwilightForest:item.ironwoodLegs
<TwilightForest:item.ironwoodLegs>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TwilightForest:item.ironwoodLegs>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TwilightForest:item.ironwoodPlate
<TwilightForest:item.ironwoodPlate>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TwilightForest:item.ironwoodPlate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<TwilightForest:item.ironwoodPlate>.addTooltip(format.aqua("Carries a camel pack."));

// TwilightForest:item.knightlyBoots
<TwilightForest:item.knightlyBoots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TwilightForest:item.knightlyBoots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TwilightForest:item.knightlyHelm
<TwilightForest:item.knightlyHelm>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TwilightForest:item.knightlyHelm>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TwilightForest:item.knightlyLegs
<TwilightForest:item.knightlyLegs>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TwilightForest:item.knightlyLegs>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TwilightForest:item.knightlyPlate
<TwilightForest:item.knightlyPlate>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TwilightForest:item.knightlyPlate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<TwilightForest:item.knightlyPlate>.addTooltip(format.aqua("Carries a camel pack."));

// TwilightForest:item.legsNaga
<TwilightForest:item.legsNaga>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TwilightForest:item.legsNaga>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TwilightForest:item.phantomHelm
<TwilightForest:item.phantomHelm>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TwilightForest:item.phantomHelm>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// TwilightForest:item.phantomPlate
<TwilightForest:item.phantomPlate>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TwilightForest:item.phantomPlate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<TwilightForest:item.phantomPlate>.addTooltip(format.aqua("Carries a camel pack."));

// TwilightForest:item.plateNaga
<TwilightForest:item.plateNaga>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<TwilightForest:item.plateNaga>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<TwilightForest:item.plateNaga>.addTooltip(format.aqua("Carries a camel pack."));

// TwilightForest:item.steeleafBoots
<TwilightForest:item.steeleafBoots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// TwilightForest:item.steeleafHelm
<TwilightForest:item.steeleafHelm>.addTooltip(format.darkAqua("Also shades you from the sun."));

// TwilightForest:item.steeleafLegs
<TwilightForest:item.steeleafLegs>.addTooltip(format.darkAqua("Also shades you from the sun."));

// TwilightForest:item.steeleafPlate
<TwilightForest:item.steeleafPlate>.addTooltip(format.darkAqua("Also shades you from the sun."));
<TwilightForest:item.steeleafPlate>.addTooltip(format.aqua("Carries a camel pack."));

// TwilightForest:item.yetiBoots
<TwilightForest:item.yetiBoots>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<TwilightForest:item.yetiBoots>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// TwilightForest:item.yetiHelm
<TwilightForest:item.yetiHelm>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<TwilightForest:item.yetiHelm>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// TwilightForest:item.yetiLegs
<TwilightForest:item.yetiLegs>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<TwilightForest:item.yetiLegs>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// TwilightForest:item.yetiPlate
<TwilightForest:item.yetiPlate>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<TwilightForest:item.yetiPlate>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<TwilightForest:item.yetiPlate>.addTooltip(format.aqua("Carries a camel pack."));

// WitchingGadgets:item.WG_AdvancedRobeChest
<WitchingGadgets:item.WG_AdvancedRobeChest>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<WitchingGadgets:item.WG_AdvancedRobeChest>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<WitchingGadgets:item.WG_AdvancedRobeChest>.addTooltip(format.aqua("Carries a camel pack."));

// WitchingGadgets:item.WG_AdvancedRobeLegs
<WitchingGadgets:item.WG_AdvancedRobeLegs>.addTooltip(format.aqua("Very warm at night. Hot in the sun."));
<WitchingGadgets:item.WG_AdvancedRobeLegs>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// WitchingGadgets:item.WG_PrimordialBoots
<WitchingGadgets:item.WG_PrimordialBoots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// WitchingGadgets:item.WG_PrimordialChest
<WitchingGadgets:item.WG_PrimordialChest>.addTooltip(format.darkAqua("Also shades you from the sun."));
<WitchingGadgets:item.WG_PrimordialChest>.addTooltip(format.aqua("Carries a camel pack."));

// WitchingGadgets:item.WG_PrimordialHelm
<WitchingGadgets:item.WG_PrimordialHelm>.addTooltip(format.darkAqua("Also shades you from the sun."));

// WitchingGadgets:item.WG_PrimordialLegs
<WitchingGadgets:item.WG_PrimordialLegs>.addTooltip(format.darkAqua("Also shades you from the sun."));

// bq_standard:loot_chest
<bq_standard:loot_chest>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<bq_standard:loot_chest>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<bq_standard:loot_chest>.addTooltip(format.aqua("Carries a camel pack."));

// enviromine:gasMask
<enviromine:gasMask>.addTooltip(format.green("Filters foul air. Full protection."));

// enviromine:hardHat
<enviromine:hardHat>.addTooltip(format.green("Filters some foul air."));

// etfuturum:bamboo_chest_raft
<etfuturum:bamboo_chest_raft>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<etfuturum:bamboo_chest_raft>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<etfuturum:bamboo_chest_raft>.addTooltip(format.aqua("Carries a camel pack."));

// etfuturum:netherite_boots
<etfuturum:netherite_boots>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<etfuturum:netherite_boots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// etfuturum:netherite_chestplate
<etfuturum:netherite_chestplate>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<etfuturum:netherite_chestplate>.addTooltip(format.darkAqua("Also shades you from the sun."));
<etfuturum:netherite_chestplate>.addTooltip(format.aqua("Carries a camel pack."));

// etfuturum:netherite_helmet
<etfuturum:netherite_helmet>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<etfuturum:netherite_helmet>.addTooltip(format.darkAqua("Also shades you from the sun."));

// etfuturum:netherite_leggings
<etfuturum:netherite_leggings>.addTooltip(format.aqua("Warm at night. Cool in the sun."));
<etfuturum:netherite_leggings>.addTooltip(format.darkAqua("Also shades you from the sun."));

// harvestcraft:hardenedleatherbootsItem
<harvestcraft:hardenedleatherbootsItem>.addTooltip(format.aqua("Warm at night. Hot in the sun."));
<harvestcraft:hardenedleatherbootsItem>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// harvestcraft:hardenedleatherchestItem
<harvestcraft:hardenedleatherchestItem>.addTooltip(format.aqua("Warm at night. Hot in the sun."));
<harvestcraft:hardenedleatherchestItem>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<harvestcraft:hardenedleatherchestItem>.addTooltip(format.aqua("Carries a camel pack."));

// harvestcraft:hardenedleatherhelmItem
<harvestcraft:hardenedleatherhelmItem>.addTooltip(format.aqua("Warm at night. Hot in the sun."));
<harvestcraft:hardenedleatherhelmItem>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// harvestcraft:hardenedleatherleggingsItem
<harvestcraft:hardenedleatherleggingsItem>.addTooltip(format.aqua("Warm at night. Hot in the sun."));
<harvestcraft:hardenedleatherleggingsItem>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));

// harvestthenether:quartzbootsItem
<harvestthenether:quartzbootsItem>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<harvestthenether:quartzbootsItem>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// harvestthenether:quartzchestItem
<harvestthenether:quartzchestItem>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<harvestthenether:quartzchestItem>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<harvestthenether:quartzchestItem>.addTooltip(format.aqua("Carries a camel pack."));

// harvestthenether:quartzhelmItem
<harvestthenether:quartzhelmItem>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<harvestthenether:quartzhelmItem>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// harvestthenether:quartzleggingsItem
<harvestthenether:quartzleggingsItem>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<harvestthenether:quartzleggingsItem>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// millenaire:item.ml_byzantineBoots
<millenaire:item.ml_byzantineBoots>.addTooltip(format.gold("Slightly cool in the sun."));
<millenaire:item.ml_byzantineBoots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// millenaire:item.ml_byzantineHelmet
<millenaire:item.ml_byzantineHelmet>.addTooltip(format.gold("Slightly cool in the sun."));
<millenaire:item.ml_byzantineHelmet>.addTooltip(format.darkAqua("Also shades you from the sun."));

// millenaire:item.ml_byzantineLegs
<millenaire:item.ml_byzantineLegs>.addTooltip(format.gold("Slightly cool in the sun."));
<millenaire:item.ml_byzantineLegs>.addTooltip(format.darkAqua("Also shades you from the sun."));

// millenaire:item.ml_byzantinePlate
<millenaire:item.ml_byzantinePlate>.addTooltip(format.gold("Slightly cool in the sun."));
<millenaire:item.ml_byzantinePlate>.addTooltip(format.darkAqua("Also shades you from the sun."));
<millenaire:item.ml_byzantinePlate>.addTooltip(format.aqua("Carries a camel pack."));

// millenaire:item.ml_japaneseGuardBoots
<millenaire:item.ml_japaneseGuardBoots>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// millenaire:item.ml_japaneseGuardHelmet
<millenaire:item.ml_japaneseGuardHelmet>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// millenaire:item.ml_japaneseGuardLegs
<millenaire:item.ml_japaneseGuardLegs>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// millenaire:item.ml_japaneseGuardPlate
<millenaire:item.ml_japaneseGuardPlate>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));
<millenaire:item.ml_japaneseGuardPlate>.addTooltip(format.aqua("Carries a camel pack."));

// millenaire:item.ml_japaneseWarriorBlueBoots
<millenaire:item.ml_japaneseWarriorBlueBoots>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// millenaire:item.ml_japaneseWarriorBlueHelmet
<millenaire:item.ml_japaneseWarriorBlueHelmet>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// millenaire:item.ml_japaneseWarriorBlueLegs
<millenaire:item.ml_japaneseWarriorBlueLegs>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// millenaire:item.ml_japaneseWarriorBluePlate
<millenaire:item.ml_japaneseWarriorBluePlate>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));
<millenaire:item.ml_japaneseWarriorBluePlate>.addTooltip(format.aqua("Carries a camel pack."));

// millenaire:item.ml_japaneseWarriorRedBoots
<millenaire:item.ml_japaneseWarriorRedBoots>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// millenaire:item.ml_japaneseWarriorRedHelmet
<millenaire:item.ml_japaneseWarriorRedHelmet>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// millenaire:item.ml_japaneseWarriorRedLegs
<millenaire:item.ml_japaneseWarriorRedLegs>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));

// millenaire:item.ml_japaneseWarriorRedPlate
<millenaire:item.ml_japaneseWarriorRedPlate>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));
<millenaire:item.ml_japaneseWarriorRedPlate>.addTooltip(format.aqua("Carries a camel pack."));

// millenaire:item.ml_mayanQuestCrown
<millenaire:item.ml_mayanQuestCrown>.addTooltip(format.gold("Punishing in the sun."));
<millenaire:item.ml_mayanQuestCrown>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// millenaire:item.ml_normanBoots
<millenaire:item.ml_normanBoots>.addTooltip(format.aqua("Warm at night."));
<millenaire:item.ml_normanBoots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// millenaire:item.ml_normanHelmet
<millenaire:item.ml_normanHelmet>.addTooltip(format.aqua("Warm at night."));
<millenaire:item.ml_normanHelmet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// millenaire:item.ml_normanLegs
<millenaire:item.ml_normanLegs>.addTooltip(format.aqua("Warm at night."));
<millenaire:item.ml_normanLegs>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// millenaire:item.ml_normanPlate
<millenaire:item.ml_normanPlate>.addTooltip(format.aqua("Warm at night."));
<millenaire:item.ml_normanPlate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<millenaire:item.ml_normanPlate>.addTooltip(format.aqua("Carries a camel pack."));

// millenaire:item.ml_skoll_hati_amulet
<millenaire:item.ml_skoll_hati_amulet>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<millenaire:item.ml_skoll_hati_amulet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// minecraft:chainmail_boots
<minecraft:chainmail_boots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<minecraft:chainmail_boots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// minecraft:chainmail_chestplate
<minecraft:chainmail_chestplate>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<minecraft:chainmail_chestplate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<minecraft:chainmail_chestplate>.addTooltip(format.aqua("Carries a camel pack."));

// minecraft:chainmail_helmet
<minecraft:chainmail_helmet>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<minecraft:chainmail_helmet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// minecraft:chainmail_leggings
<minecraft:chainmail_leggings>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<minecraft:chainmail_leggings>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// minecraft:diamond_boots
<minecraft:diamond_boots>.addTooltip(format.darkAqua("Also shades you from the sun."));

// minecraft:diamond_chestplate
<minecraft:diamond_chestplate>.addTooltip(format.darkAqua("Also shades you from the sun."));
<minecraft:diamond_chestplate>.addTooltip(format.aqua("Carries a camel pack."));

// minecraft:diamond_helmet
<minecraft:diamond_helmet>.addTooltip(format.darkAqua("Also shades you from the sun."));

// minecraft:diamond_leggings
<minecraft:diamond_leggings>.addTooltip(format.darkAqua("Also shades you from the sun."));

// minecraft:golden_boots
<minecraft:golden_boots>.addTooltip(format.gold("Punishing in the sun."));
<minecraft:golden_boots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// minecraft:golden_chestplate
<minecraft:golden_chestplate>.addTooltip(format.gold("Punishing in the sun."));
<minecraft:golden_chestplate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<minecraft:golden_chestplate>.addTooltip(format.aqua("Carries a camel pack."));

// minecraft:golden_helmet
<minecraft:golden_helmet>.addTooltip(format.gold("Punishing in the sun."));
<minecraft:golden_helmet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// minecraft:golden_leggings
<minecraft:golden_leggings>.addTooltip(format.gold("Punishing in the sun."));
<minecraft:golden_leggings>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// minecraft:iron_boots
<minecraft:iron_boots>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<minecraft:iron_boots>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// minecraft:iron_chestplate
<minecraft:iron_chestplate>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<minecraft:iron_chestplate>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
<minecraft:iron_chestplate>.addTooltip(format.aqua("Carries a camel pack."));

// minecraft:iron_helmet
<minecraft:iron_helmet>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<minecraft:iron_helmet>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// minecraft:iron_leggings
<minecraft:iron_leggings>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<minecraft:iron_leggings>.addTooltip(format.darkAqua("Also conducts the sun's heat."));

// minecraft:leather_boots
<minecraft:leather_boots>.addTooltip(format.aqua("Warm at night. Hot in the sun."));

// minecraft:leather_chestplate
<minecraft:leather_chestplate>.addTooltip(format.aqua("Warm at night. Hot in the sun."));
<minecraft:leather_chestplate>.addTooltip(format.aqua("Carries a camel pack."));

// minecraft:leather_helmet
<minecraft:leather_helmet>.addTooltip(format.aqua("Warm at night. Hot in the sun."));

// minecraft:leather_leggings
<minecraft:leather_leggings>.addTooltip(format.aqua("Warm at night. Hot in the sun."));

// powersuits:item.powerArmorBoots
<powersuits:item.powerArmorBoots>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));
<powersuits:item.powerArmorBoots>.addTooltip(format.green("Filters some foul air."));

// powersuits:item.powerArmorChestplate
<powersuits:item.powerArmorChestplate>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));
<powersuits:item.powerArmorChestplate>.addTooltip(format.green("Filters some foul air."));
<powersuits:item.powerArmorChestplate>.addTooltip(format.aqua("Carries a camel pack."));

// powersuits:item.powerArmorHelmet
<powersuits:item.powerArmorHelmet>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));
<powersuits:item.powerArmorHelmet>.addTooltip(format.green("Filters foul air. Full protection."));

// powersuits:item.powerArmorLeggings
<powersuits:item.powerArmorLeggings>.addTooltip(format.darkAqua("Also insulates against cold and shades you from the sun."));
<powersuits:item.powerArmorLeggings>.addTooltip(format.green("Filters some foul air."));

// xreliquary:harvest_rod
<xreliquary:harvest_rod>.addTooltip(format.aqua("Warm at night. Hot in the sun."));
<xreliquary:harvest_rod>.addTooltip(format.darkAqua("Also insulates against cold and conducts the sun's heat."));
<xreliquary:harvest_rod>.addTooltip(format.aqua("Carries a camel pack."));

// xreliquary:witch_hat
<xreliquary:witch_hat>.addTooltip(format.gray("Cold at night. Punishing in the sun."));
<xreliquary:witch_hat>.addTooltip(format.darkAqua("Also conducts the sun's heat."));
