#!/usr/bin/env python3
"""Emit armour.zs from the LIVE EnviroMine config.

Text is derived from each item's actual numbers, not from the material class it
was assigned. That means vanilla armour and the hand-tuned sets (copper, tin,
lead, nickel, invar, scorpion, fur, millenaire) get truthful tooltips too --
they were previously skipped because the generator only described items it had
itself classified.

If a value is ever retuned, regenerate; the description cannot drift.
"""
import glob, re, sys

CP = "/home/duduserver/minecraft/1.7.10/config/enviromine/profiles/default/CustomProperties"

def entries():
    out = {}
    for f in glob.glob(f"{CP}/*.cfg"):
        s = re.search(r"^armor \{$(.*?)^\}$", open(f).read(), re.S | re.M)
        if not s:
            continue
        for b in re.finditer(r"\{\s*\n\s*S:01\.ID=([\w.:\-]+)\n(.*?)\n    \}", s.group(1), re.S):
            ident, body = b.groups()
            v = dict(re.findall(r'[BD]:"?\d+\.([\w \-]+?)"?=(-?[\d.]+|true|false)', body))
            out[ident] = v
    return out

def num(v, k, d=0.0):
    try: return float(v.get(k, d))
    except ValueError: return d

def describe(v):
    night = num(v, "Temp Add - Night"); sun = num(v, "Temp Add - Sun")
    xn = num(v, "Temp Multiplier - Night", 1.0); xs = num(v, "Temp Multiplier - Sun", 1.0)
    air = num(v, "Air"); camel = v.get("Allow Camel Pack") == "true"
    lines = []

    warm = ("Very warm at night." if night >= 1.5 else
            "Warm at night."      if night >= 0.75 else
            "Slightly warm at night." if night >= 0.25 else
            "Cold at night."      if night <= -0.75 else
            "Slightly cold at night." if night <= -0.25 else "")
    hot  = ("Punishing in the sun." if sun >= 1.75 else
            "Hot in the sun."       if sun >= 0.75 else
            "Slightly hot in the sun." if sun >= 0.25 else
            "Cool in the sun."      if sun <= -0.75 else
            "Slightly cool in the sun." if sun <= -0.25 else "")
    t = " ".join(x for x in (warm, hot) if x)
    if t:
        col = "aqua" if night >= 0.25 else "gray" if night <= -0.25 else "gold"
        lines.append((col, t))

    ins = []
    if xn <= 0.95:  ins.append("insulates against cold")
    if xs <= 0.95:  ins.append("shades you from the sun")
    if xs >= 1.05:  ins.append("conducts the sun's heat")
    if ins:
        lines.append(("darkAqua", "Also " + " and ".join(ins) + "."))

    if air >= 0.75:   lines.append(("green", "Filters foul air. Full protection."))
    elif air > 0:     lines.append(("green", "Filters some foul air."))
    if camel:         lines.append(("aqua", "Carries a camel pack."))
    return lines

def main():
    e = entries()
    print("// ==========================================================================")
    print("//  armour.zs - GENERATED by gen_armour_tooltips.py from the live EnviroMine")
    print("//  config. Every line is derived from that item's real numbers, so the text")
    print("//  cannot disagree with what the game actually does. Regenerate after any")
    print("//  retune; never hand-edit.")
    print("//")
    print("//  Covers vanilla and hand-tuned sets too - anything with an armour entry.")
    print("//  Must be identical on server and every client: tooltips do not sync.")
    print("// ==========================================================================")
    n = 0
    for ident in sorted(e):
        lines = describe(e[ident])
        if not lines: continue
        print(f"\n// {ident}")
        for col, txt in lines:
            print(f'<{ident}>.addTooltip(format.{col}("{txt}"));')
            n += 1
    print(f"\n// {n} tooltip lines across {len(e)} armour items", file=sys.stderr)

main()
